exclusive/urls.py
from django.urls import path
from .views import *
from django.urls import path


app_name = 'course'
urlpatterns = [
    path('', CourseIndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('signup/', SignupView.as_view(), name='signup'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('courses/', CoursesView.as_view(), name='courses'),
    path('courses/<slug:course_slug>', CourseDetailView.as_view(), name='course_detail'),
    path('lessons/<slug:course_slug>', LessonsView.as_view(), name='lessons'),
    path('lessons/<slug:course_slug>/<slug:lesson_slug>', LessonDetailView.as_view(), name='lesson'),
    path('faqs/', FAQsView.as_view(), name='faqs'),
    path('contact/', ContactView.as_view(), name='contact'),
    path('pricing/', PricingView.as_view(), name='pricing'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('confirm-payment/', ConfirmPaymentView.as_view(), name='confirm_payment'),
    path('logout/', LogoutView.as_view(), name='logout'),
     path('password_reset/', password_reset_request, name='password_reset'),
    path('password_reset/done/', password_reset_done, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', password_reset_confirm, name='password_reset_confirm'),
    path('reset/done/', password_reset_complete, name='password_reset_complete'),
]

jiva_exclusive/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("exclusive.urls")),
    path("event-registration/", include("registration.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exclusive/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    """
    Model for user profiles: user, bio, profile pic
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    phone_number = models.CharField(max_length=20, blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    registered = models.BooleanField(default=False)
    intermediate_access = models.BooleanField(default=False)
    advanced_access = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user.first_name}'s Profile"


class Course(models.Model):
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    mini_description = models.CharField(max_length=150)
    description = models.TextField()
    thumbnail = models.ImageField(upload_to='course_images')
    level = models.CharField(max_length=50)
    year = models.IntegerField(validators=[MinValueValidator(2019), MaxValueValidator(2090)], default=2021)
    core = models.BooleanField(default=False)
    course_number = models.IntegerField(unique=True, blank=True, null=True, validators=[MinValueValidator(0), MaxValueValidator(5)])

    def __str__(self):
        return self.title


# class Enrollment(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='enrollments')
#     course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='enrollments')
#     created_at = models.DateTimeField(auto_now_add=True)
#
#     def __str__(self):
#         return f'{self.user} - {self.course}'


class Lesson(models.Model):
    TYPE_CHOICES = (
        ('lesson', 'Lesson'),
        ('supplementary', 'supplementary'),
        ('q&a', 'Q&A'),
    )
    lesson_number = models.IntegerField()
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=50, unique=True)
    slug = models.SlugField(max_length=50, unique=True)
    description = models.TextField()
    lesson_type = models.CharField(max_length=50, choices=TYPE_CHOICES, default='lesson')
    thumbnail = models.ImageField(upload_to='lesson_thumbnails')
    video_source = models.CharField(max_length=50, choices=(('youtube', 'Y'), ('vimeo', 'V')))
    video_id = models.CharField(max_length=100)
    twi_video_id = models.CharField(max_length=50, blank=True)

    def __str__(self):
        return self.title


# class AccessCode(models.Model):
#     """
#     Model for access codes to courses: unique 5-digit code; can access one or more courses
#     """
#     code = models.CharField(max_length=5, unique=True)
#     courses = models.ManyToManyField(Course)
#
#     def __str__(self):
#         return self.code


class Payment(models.Model):
    """
    Model for payments: user, main, amount, date
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='payments')
    amount = models.DecimalField(max_digits=6, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.amount} - {self.date}'
    
    
class Comment(models.Model):
    name = models.CharField(max_length=155)
    email = models.EmailField()
    message = models.TextField()
    
    def __str__(self):
        return f'{self.name} - Comment'

exclusive/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm

class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        label="Email",
        max_length=254,
        widget=forms.EmailInput(attrs={
            'class': 'form-control flq-form-mail flq-form-translucent',
            'placeholder': 'Email',
            'required': 'required'
        })
    )

exclusive/views.py
import json
from django.http import HttpResponseRedirect
from django.urls import reverse
import requests
from django import forms
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import send_mail

from .models import *
from .decorators import require_registered_user


# class IndexView(View):
#     template_name = 'exclusive/index.html'
#
#     def get(self, request):
#         courses_ = Course.objects.all()
#         context = {
#             "courses": courses_
#         }
#         return render(request, self.template_name, context)


class CourseIndexView(View):
    template_name = 'exclusive/main-landing.html'

    # login_url = '/login/'

    def get(self, request):
        courses_ = Course.objects.all()
        context = {
            "courses": courses_
        }
        return render(request, self.template_name, context)


class CoursesView(LoginRequiredMixin, View):
    template_name = 'exclusive/pathways.html'
    login_url = '/login/'

    @require_registered_user
    def get(self, request):
        courses_ = Course.objects.filter(core=True).order_by('course_number')
        context = {
            'courses': courses_,
        }
        return render(request, self.template_name, context)


class CourseDetailView(LoginRequiredMixin, View):
    template_name = 'exclusive/single-course.html'
    login_url = '/login/'

    @require_registered_user
    def get(self, request, course_id):
        return render(request, self.template_name)


class LessonsView(LoginRequiredMixin, View):
    template_name = 'exclusive/lessons.html'
    login_url = '/login/'

    @require_registered_user
    def get(self, request, course_slug):
        course_ = Course.objects.get(slug=course_slug)
        course_lessons = course_.lessons.all()

        context = {
            'course': course_,
            'course_lessons': course_lessons,
        }
        return render(request, self.template_name, context)


class LessonDetailView(LoginRequiredMixin, View):
    template_name = 'exclusive/single-lesson.html'
    login_url = '/login/'

    @require_registered_user
    def get(self, request, course_slug, lesson_slug):
        course = Course.objects.get(slug=course_slug)
        lesson = Lesson.objects.get(slug=lesson_slug)
        course_lessons = course.lessons.all()

        next_lesson = lesson.lesson_number + 1
        if next_lesson <= course.lessons.count():
            next_lesson = course.lessons.get(lesson_number=next_lesson)
        else:
            next_lesson = None

        twi = False
        if request.GET.get('language') and request.GET.get('language') == 'twi':
            twi = True

        context = {
            'course': course,
            'lesson': lesson,
            'course_lessons': course_lessons,
            'next_lesson': next_lesson,
            'twi': twi
        }
        return render(request, self.template_name, context)


class FAQsView(View):
    template_name = 'exclusive/faq.html'

    def get(self, request):
        return render(request, self.template_name)


class ContactView(View):
    template_name = 'exclusive/contact.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")

        Comment.objects.create(name, email, message)

        # Reverse the URL to redirect after the comment is created
        return HttpResponseRedirect(reverse('comment_success'))


class PricingView(View):
    template_name = 'exclusive/pricing.html'

    def get(self, request):
        # if the user is already registered, redirect to the course index
        if request.user.is_authenticated and request.user.profile.registered:
            return redirect('course:index')
        return render(request, self.template_name)


# =============================================== Payment ===============================================

class CheckoutView(LoginRequiredMixin, View):
    template_name = 'exclusive/payment.html'
    login_url = '/login/'

    def get(self, request):
        amount = 300000
        email = request.user.email

        url = "https://api.paystack.co/transaction/initialize"

        payload = json.dumps({
            "email": email,
            "amount": amount,
            "callback_url": "https://awake.drbaffourjan.com/confirm-payment",
            "split_code": "SPL_NB7LnX54qz",
            "channels": [
                "card",
                "mobile_money"
            ]
        })
        headers = {
            'Content-Type': 'application/json',
            'Authorization': f'Bearer {settings.PAYSTACK_SECRET_KEY}'
        }

        response = requests.request("POST", url, headers=headers, data=payload)
        response_data = response.json()
        print(response_data)
        return redirect(response_data['data']['authorization_url'])


class ConfirmPaymentView(LoginRequiredMixin, View):
    template_name = 'exclusive/confirm-payment.html'
    login_url = '/login/'

    def get(self, request):
        context = {}
        reference = request.GET.get('reference')
        trxref = request.GET.get('trxref')

        url = f"https://api.paystack.co/transaction/verify/{reference}"

        headers = {
            'Authorization': f'Bearer {settings.PAYSTACK_SECRET_KEY}',
        }

        response = requests.request("GET", url, headers=headers)
        response_data = response.json()

        status = response_data['data']['status']
        amount = response_data['data']['amount']

        context['status'] = status

        if status == 'success':
            # update the user registration status
            user = request.user
            user.profile.registered = True
            user.profile.save()

            # save in payments
            print(amount)
            p = Payment(user=user, amount=amount/100)
            p.save()

        return render(request, self.template_name, context)


# =============================================== Auth ===============================================
class LoginView(View):
    template_name = 'exclusive/login.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        email = request.POST.get("email")
        password = request.POST.get("password")

        try:
            user = User.objects.get(email=email)
        except User.DoesNotExist:
            return render(request, self.template_name, {'error': 'Invalid email or password'})

        if user.check_password(password):
            auth_user = authenticate(request, username=user.username, password=password)
            if auth_user is not None:
                login(request, auth_user)
                return redirect('course:index')  # todo: if the user is not registered redirect to pricing
        return render(request, self.template_name, {'error': 'Invalid email or password'})


class SignupView(View):
    template_name = 'exclusive/signup.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        full_name = request.POST.get('full_name')
        email = request.POST.get('email')
        password = request.POST.get('password')

        if User.objects.filter(email=email).exists():
            return render(request, self.template_name, {'error': 'Email is already registered. Try Logging in.'})

        user = User.objects.create_user(username=email.split("@")[0], email=email, password=password)

        try:
            user.first_name, user.last_name = full_name.split(maxsplit=1)
        except ValueError:
            user.first_name = full_name

        user.save()

        profile = Profile(user=user)
        profile.save()

        login(request, user)

        return redirect('course:index')
        # return redirect('course:checkout')


class ProfileView(LoginRequiredMixin, View):
    template_name = 'exclusive/account-profile.html'
    login_url = "/login/"

    def get(self, request):
        # get current user
        user = request.user
        context = {
            "user": user
        }
        return render(request, self.template_name, context)


class LogoutView(View):

    def get(self, request):
        logout(request)
        return redirect('course:login')


# =========================================== password reset ==============================================
def password_reset_request(request):
    error = None
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(email=data)
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "exclusive/password/password_reset_email.html"
                    c = {
                        "email": user.email,
                        'domain': get_current_site(request).domain,
                        'site_name': 'Your Site Name',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,

exclusive/templates/exclusive/account-profile.html
{% extends 'exclusive/base.html' %}
{% load static %}

{% block navbar_fixed %}
{% endblock %}

{% block content %}
<div class="content-wrap">
    <div class="container pt-5 pb-7">
        <div class="row gy-6 gx-6">
            <div class="col-12 col-xl order-5">
                <div class="flq-account-content">
                            <span class="flq-account-avatar mb-4">
                                <span class="flq-image flq-responsive flq-responsive-1x1 flq-rounded">
                                    <img src="{% static 'exclusive/assets/images/profile.jpg' %}" alt="">
                                </span>
                            </span>
                    <table class="table">
                        <tbody>
                        <tr>
                            <td class="flq-color-meta">First Name</td>
                            <td>{{ user.first_name }}</td>
                        </tr>
                        <tr>
                            <td class="flq-color-meta">Last Name</td>
                            <td>{{ user.last_name }}</td>
                        </tr>
                        <tr>
                            <td class="flq-color-meta">Email</td>
                            <td>{{ user.email }}</td>
                        </tr>
                        {% comment %}
                        <tr>
                            <td class="flq-color-meta">Country</td>
                            <td>Null</td>
                        </tr>
                        <tr>
                            <td class="flq-color-meta">City</td>
                            <td>Null</td>
                        </tr>
                        <tr>
                            <td class="flq-color-meta">Gender</td>
                            <td>Null</td>
                        </tr>
                        <tr>
                            <td class="flq-color-meta">Date of Birth</td>
                            <td>
                                <div class="row">
                                    <div class="col-auto">November 29, 1990</div>
                                    <div class="col-auto flq-color-meta">30 years</div>
                                </div>
                            </td>
                        </tr>
                        {% endcomment %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="col-12 col-xl-auto">
                <div class="flq-sidebar flq-sidebar-lg">
                    <div class="flq-account-navbar">
                        <nav>
                            <ul class="nav nav-dots flex-column gy-3">
                                <li class="nav-item active">
                                    <a href="{% url 'course:profile' %}" class="nav-link">
                                        <span class="nav-link-name">Profile</span>
                                    </a>
                                </li>
                                {% comment %}
                                <li class="nav-item">
                                    <a href="account-favorites.html" class="nav-link">
                                        <span class="nav-link-name">Favorites</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="account-reviews.html" class="nav-link">
                                        <span class="nav-link-name">Reviews &amp; Comments</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="account-edit.html" class="nav-link">
                                        <span class="nav-link-name">Account Edit</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="account-notifications.html" class="nav-link">
                                        <span class="nav-link-name">Notifications</span>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a href="account-logout.html" class="nav-link">
                                        <span class="nav-link-name">Logout</span>
                                    </a>
                                </li>
                                {% endcomment %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer -->
    {% include 'exclusive/utilities/footer.html' %}
    <!-- /Footer -->
</div>
{% endblock %}

exclusive/templates/exclusive/contact.html
{% extends 'exclusive/base.html' %}
{% load static %}

{% block navbar_fixed %}
{% endblock %}

{% block content %}
        <div class="flq-background py-md-7 py-6" style="background: linear-gradient(to bottom, rgba(0,0,0,0.7), rgba(0,0,0,0.9)), url('{% static 'exclusive/assets/images/background/test-1.jpg' %}'); background-size: cover; background-position: center">
            <div class="container text-center">
                <h1 class="display-6 mb-1 d-none d-md-block">Need Help ?</h1>
                <h2 class="mb-1 d-md-none">Need Help ?</h2>
                <p class="">Questions ? Suggestions ?</p>
            </div>
        </div>
        <div class="content-wrap">
            <div class="pt-7">
                <div class="container">
                    <div class="row gy-4 justify-content-center" data-sr="card-feature" data-sr-interval="100" data-sr-duration="1000" data-sr-distance="10">
                        <div class="col-12 col-md-6 col-lg" data-sr-item="card-feature">
                            <div class="card flq-card-feature flq-card-feature-filled text-center">
                                <div class="card-body">
                                    <div class="card-icon">
                                        <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M26.25 12.5C26.25 21.25 15 28.75 15 28.75C15 28.75 3.75 21.25 3.75 12.5C3.75 9.51631 4.93526 6.65483 7.04505 4.54505C9.15483 2.43526 12.0163 1.25 15 1.25C17.9837 1.25 20.8452 2.43526 22.955 4.54505C25.0647 6.65483 26.25 9.51631 26.25 12.5ZM15 16.25C17.0711 16.25 18.75 14.5711 18.75 12.5C18.75 10.4289 17.0711 8.75 15 8.75C12.9289 8.75 11.25 10.4289 11.25 12.5C11.25 14.5711 12.9289 16.25 15 16.25Z" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                        <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M26.25 12.5C26.25 21.25 15 28.75 15 28.75C15 28.75 3.75 21.25 3.75 12.5C3.75 9.51631 4.93526 6.65483 7.04505 4.54505C9.15483 2.43526 12.0163 1.25 15 1.25C17.9837 1.25 20.8452 2.43526 22.955 4.54505C25.0647 6.65483 26.25 9.51631 26.25 12.5ZM15 16.25C17.0711 16.25 18.75 14.5711 18.75 12.5C18.75 10.4289 17.0711 8.75 15 8.75C12.9289 8.75 11.25 10.4289 11.25 12.5C11.25 14.5711 12.9289 16.25 15 16.25Z" fill="currentColor" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                    </div>
                                    <div class="card-title h5">Visit Us</div>
                                    <p>Franko Estate, Pokuase</p>
                                    <p>Greater Accra - hana</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-12 col-md-6 col-lg" data-sr-item="card-feature">
                            <a href="#" class="card flq-card-feature flq-card-feature-filled text-center">
                                <span class="card-body">
                                    <span class="card-icon">
                                        <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M18.8125 6.25C20.0335 6.48821 21.1555 7.08532 22.0351 7.96492C22.9147 8.84452 23.5118 9.96658 23.75 11.1875M18.8125 1.25C21.3491 1.5318 23.7145 2.66772 25.5203 4.47126C27.3262 6.2748 28.4651 8.63876 28.75 11.175M27.5 21.15V24.9C27.5015 25.2481 27.4301 25.5927 27.2907 25.9117C27.1512 26.2307 26.9467 26.517 26.6901 26.7523C26.4336 26.9877 26.1308 27.1669 25.801 27.2784C25.4712 27.3899 25.1218 27.4313 24.775 27.4C20.9286 26.9821 17.2338 25.6677 13.9875 23.5625C10.9673 21.6433 8.40671 19.0827 6.48754 16.0625C4.37501 12.8015 3.06034 9.08874 2.65004 5.225C2.6188 4.87933 2.65988 4.53095 2.77066 4.20203C2.88145 3.87311 3.0595 3.57086 3.2935 3.31453C3.52749 3.05819 3.81229 2.85339 4.12978 2.71315C4.44726 2.57292 4.79046 2.50033 5.13754 2.5H8.88754C9.49417 2.49403 10.0823 2.70885 10.5422 3.10442C11.0022 3.49998 11.3026 4.04931 11.3875 4.65C11.5458 5.85008 11.8394 7.02841 12.2625 8.1625C12.4307 8.60991 12.4671 9.09614 12.3674 9.5636C12.2677 10.0311 12.0361 10.4601 11.7 10.8L10.1125 12.3875C11.892 15.5169 14.4831 18.1081 17.6125 19.8875L19.2 18.3C19.5399 17.9639 19.969 17.7323 20.4364 17.6326C20.9039 17.5329 21.3901 17.5693 21.8375 17.7375C22.9716 18.1607 24.15 18.4542 25.35 18.6125C25.9572 18.6982 26.5118 19.004 26.9082 19.4719C27.3046 19.9397 27.5152 20.537 27.5 21.15Z" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                        <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M27.5003 24.9V21.15C27.5155 20.537 27.3049 19.9397 26.9084 19.4719C26.512 19.004 25.9575 18.6982 25.3503 18.6125C24.1502 18.4542 22.9719 18.1607 21.8378 17.7375C21.3904 17.5693 20.9041 17.5329 20.4367 17.6326C19.9692 17.7323 19.5401 17.9639 19.2003 18.3L17.6128 19.8875C14.4834 18.1081 11.8922 15.5169 10.1128 12.3875L11.7003 10.8C12.0364 10.4601 12.268 10.0311 12.3677 9.5636C12.4674 9.09614 12.431 8.6099 12.2628 8.1625C11.8396 7.02841 11.5461 5.85008 11.3878 4.65C11.3029 4.04931 11.0024 3.49998 10.5425 3.10441C10.0825 2.70885 9.49442 2.49403 8.88778 2.5H5.13778C4.79071 2.50033 4.4475 2.57292 4.13002 2.71315C3.81254 2.85339 3.52773 3.05819 3.29374 3.31453C3.05975 3.57086 2.88169 3.87311 2.77091 4.20203C2.66013 4.53095 2.61905 4.87933 2.65028 5.225C3.06059 9.08874 4.37526 12.8015 6.48778 16.0625C8.40695 19.0827 10.9676 21.6433 13.9878 23.5625C17.234 25.6677 20.9288 26.982 24.7753 27.4C25.122 27.4313 25.4714 27.3899 25.8012 27.2784C26.131 27.1669 26.4339 26.9877 26.6904 26.7523C26.9469 26.517 27.1515 26.2307 27.2909 25.9117C27.4304 25.5927 27.5017 25.2481 27.5003 24.9Z" fill="currentColor" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                    </span>
                                    <span class="card-title h5">Call Us</span>
                                    <span class="paragraph">+233 550590054</span>
                                    <span class="paragraph"># 1001</span>
                                </span>
                            </a>
                        </div>
                        <div class="col-12 col-md-6 col-lg" data-sr-item="card-feature">
                            <a href="#" class="card flq-card-feature flq-card-feature-filled text-center">
                                <span class="card-body">
                                    <span class="card-icon">
                                        <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path d="M27.5 7.5C27.5 6.125 26.375 5 25 5H5C3.625 5 2.5 6.125 2.5 7.5M27.5 7.5V22.5C27.5 23.875 26.375 25 25 25H5C3.625 25 2.5 23.875 2.5 22.5V7.5M27.5 7.5L15 16.25L2.5 7.5" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" />
                                        </svg>
                                        <svg width="30" height="30" viewBox="0 0 30 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                                            <path fill-rule="evenodd" clip-rule="evenodd" d="M3.88322 6.94244L15 14.7242L26.1168 6.94244C25.9101 6.53365 25.485 6.25 25 6.25H5C4.51505 6.25 4.08995 6.53365 3.88322 6.94244ZM1.25 7.5C1.25 5.43464 2.93464 3.75 5 3.75H25C27.0654 3.75 28.75 5.43464 28.75 7.5V22.5C28.75 24.5654 27.0654 26.25 25 26.25H5C2.93464 26.25 1.25 24.5654 1.25 22.5V7.5Z" fill="currentColor" />
                                        </svg>
                                    </span>
                                    <span class="card-title h5">Write Us</span>
                                    <span class="paragraph">drbaffourjan@gmail.com</span>
                                    <span class="paragraph">info@jcfghana.com</span>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="py-7">
                <div class="container-small">
                    <div class="text-center mb-5" data-sr="contact-text" data-sr-interval="100" data-sr-duration="1000" data-sr-distance="10">
                        <span class="flq-subtitle badge" data-sr-item="contact-text">Contact Form</span>
                        <h2 class="display-6" data-sr-item="contact-text">Leave a Message</h2>
                    </div>
                    <form action="{% url 'course:contact' %}" method="post">
                        <div class="row gy-4" data-sr="contact-form" data-sr-interval="100" data-sr-duration="1000" data-sr-distance="10">
                            <div class="col-12 col-sm" data-sr-item="contact-form">
                                <input class="form-control flq-form-user form-control-lg" type="text" placeholder="Your Name" name="name" required>
                            </div>
                            <div class="col-12 col-sm" data-sr-item="contact-form">
                                <input class="form-control flq-form-mail form-control-lg" type="email" placeholder="Your Email" name="email" required>
                            </div>
                            <div class="col-12" data-sr-item="contact-form">
                                <textarea class="form-control flq-form-message form-control-lg" rows="5" placeholder="Your Message" name="message"></textarea>
                            </div>
                            <div class="col-12" data-sr-item="contact-form">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="contact_form"><label class="form-check-label" for="contact_form">Save my name, email, and website in this browser for the next time I comment.</label>
                                </div>
                            </div>
                            <div class="col-12" data-sr-item="contact-form">
                                <button class="btn btn-lg btn-block">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            {% include 'exclusive/utilities/footer.html' %}
        </div>
{% endblock %}